### PR TITLE
support touch screens

### LINKED ISSUE #6: Is there a way to make it work with iOS and Android?
On touch.

### PR DESCRIPTION
**Pull request by makc**
fixes #6 and took me like 10 minutes

### CODE REVIEW

**Comment by thdoan** [comment]
Thanks @makc I will merge your PR.

**Comment by makc** [comment]
@thdoan by the way we ended up using different (and more hacky) version of this:
```javascript
                nX = e.pageX - oMagnifyOffset.left,
                nY = e.pageY - oMagnifyOffset.top;
              if (e.originalEvent.touches) {
                nX = e.originalEvent.touches[0].pageX - 100 - oMagnifyOffset.left; if ((nX < 1) && (nX > -100)) nX = 1;
                nY = e.originalEvent.touches[0].pageY - 100 - oMagnifyOffset.top;  if ((nY < 1) && (nY > -100)) nY = 1;
              }
```
this is so that finger would not obscure the view. Not sure how to implement that in clean manner, up to you :)

**Comment by thdoan** [comment]
Well, this is a tricky one that could be subjective. For example, one offset may work for right-handers, but not for lefties. For the time being I'll leave it as is because I quite like the current glitch (lens still shows when you release your finger) since it allows people to view the zoomed image after releasing their finger so that it doesn't obstruct the view :).

**Comment by makc** [comment]
> I'll leave it as is because I quite like the current glitch (lens still shows when you release your finger) since it allows people to view the zoomed image after releasing their finger 

yes, that makes sense.

**Pull request closed without merging**
