### PR TITLE
Mobile only offset touch point to be at the bottom instead of the center

### PR DESCRIPTION
**Pull request by mylastore**
I tested this on iPhone 8 on latest Safari & Firefox browsers.

### CODE REVIEW

**Comment by reachdevelopers** [comment]
Added also as an option.

**Comment by thdoan** [comment]
Thanks, I'll roll this into the next release.

**Comment by thdoan** [comment]
FYI instead of setting `isMobile` from inside that event handler, which would be executed every X milliseconds as move your mouse/finger around, I'm going to define it outside the handler. I will also rename the flag to `isTouch` based on 'touch' from my bag of browser tricks:

```
var browser = {
    '3d': testCss('perspective', 'Perspective'),
    'addEventListener': !!window.addEventListener,
    'animations': testCss('animationName', 'AnimationName'),
    'canvas': !!window.CanvasRenderingContext2D,
    'filter': testCss('filter', '', 'filter:saturate(2)'),
    'flexbox': testCss('flexWrap', 'FlexWrap'),
    'gradients': testCss('backgroundImage', '', 'background-image:linear-gradient(black,white),radial-gradient(black,white)'),
    'svg': typeof SVGRect!=='undefined',
    'touch': !!('ontouchstart' in window || (window.DocumentTouch && document instanceof DocumentTouch) || navigator.msMaxTouchPoints),
    'transitions': testCss('transitionProperty', 'Transition'),
    'vw': testCss('width', '', 'width:100vw')
  };
```

**Comment by reachdevelopers** [comment]
Awesome thanks.

**Comment by reachdevelopers** [comment]
nice! is working on the latest iOS on Safari, Chrome, and Firefox.  Awesome project thanks.

**Comment by thdoan** [comment]
Thanks for the feature suggestion :-).

**Pull request merged**
